server:
  port: 10000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Seguridad
SIGN_REQUIRE_API_KEY: true
SIGN_API_KEY_HEADER: x-api-key
# En Render: define SIGN_API_KEYS como variable de entorno (p.ej. "k1,k2")
